spring:
  datasource:
    url: jdbc:h2:tcp://localhost/C:\data\user-service # jdbc:h2:file:C:\data\test
    username: sa
    password:

token:
  expiration_time: 10000000
  secret: user_token_local_changed#2

gateway:
  ip: 192.168.0.7