version: "2"

services:
  config-service:
    image: gramman75/config-service:1.0
    container_name: config-service
    environment:
      spring.rabbitmq.host: rabbitmq
    ports:
      - 8888:8888
    networks:
      - my-network

networks:
  my-network:
    name: ecommerce-network