version: "3"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - D:\data\mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: mariadb
    networks:
      - my-network
networks:
  my-network:
    name: ecommerce-network